### ISSUE TITLE
这个

### ISSUE THREAD

**Issue by shangguanwt** [omarzanji/gesture-recognition#4]
![image](https://user-images.githubusercontent.com/111739854/204179708-7f8c030e-4f17-4a29-ba59-fb5128274d69.png)

**Comment by omarzanji** [comment]
Sorry, I updated the model. Please delete the models/ folder and run `git pull`. Then run `main.py` to download latest model to resolve your problem. Let me know if this worked for you and I can close the issue. Thank you!

**Comment by shangguanwt** [comment]
> Sorry, I updated the model. Please delete the models/ folder and run `git pull`. Then run main.py to download latest model to resolve your problem. Let me know if this worked for you and I can close the issue. Thank you!
Hello, I'm still a beginner, so I don't know much about deep learning. I don't know whether the running result is correct. I hope you can give me more guidance. Thank you!
![image](https://user-images.githubusercontent.com/111739854/204277220-26882ebd-fd91-4e43-8f4a-4b6fffe55350.png)

**Comment by omarzanji** [comment]
I have tested running main on two machines and verified it works on main branch. 
Can you please try the following:

1. Delete the repository and clone again.
2. Run the following:
`pip install -r requirements.txt`
`python main.py`

If this does not work you can try:
`pip install tensorflow==2.10.0`
and 
`pip install numpy --upgrade`

Let me know if this works for you!

**Comment by shangguanwt** [comment]
> I have tested running main on two machines and verified it works on main branch. Can you please try the following:
> 
> 1. Delete the repository and clone again.
> 2. Run the following:
>    `pip install -r requirements.txt`
>    `python main.py`
> 
> If this does not work you can try: `pip install tensorflow==2.10.0` and `pip install numpy --upgrade`
> 
> Let me know if this works for you!

After constant debugging, it has been running successfully, and this image will be a bit stuck and delayed. I don't know if there is anything wrong with my operation. Thank you for your guidance, thank you!

**Comment by omarzanji** [comment]
That's great! I made an adjustment to line 169 in `main.py` so that the refresh rate can be 30ms instead of 300ms. It is set slow because you do not need fast frame captures to successfully identify the gesture. The larger the refresh rate the less computation on your machine. Have fun! Feel free to adjust line 169 to your liking:

```python
cv2.waitKey(30) # 1000 ms = 1 second 
```

be sure to `git pull` to get this update.
Thank you!
